### ISSUE TITLE
When will the training code for PARCNet be released?

### ISSUE THREAD

**Issue by Janne-byti** [ilic-mezza/polyphonic_rhythm_complexity#2]
Hello, I am researching the PLC algorithm and have tried the pre trained model you provided, which has shown good results. However, I would like to train myself on a dataset and would like to know when you will update the training code?

**Comment by ilic-mezza** [comment]
Hi @Janne-byti,

This is not the PARCnet repo, so I'm going to close this issue.

However, I've seen you opened an issue on [https://github.com/polimi-ispl/PARCnet/issues](https://github.com/polimi-ispl/PARCnet/issues/2); I will reply to that one instead.
